apiVersion: apps/v1
kind: Deployment
metadata:
  name: greetings 
  labels:
    app: greetings
spec:
  replicas: 2
  selector:
    matchLabels:
      app: greetings
  template:
    metadata:
      labels:
        app: greetings
    spec:
      serviceAccount: greetings
      volumes:
        - name: hostfolder-volume
          configMap:
            name: greetings-config
      containers:
        - name: assignment5
          image: "jkm3488:assignment5"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
          env:
            - name: GREETING
              value: "Fall is here."
          volumeMounts:
            - name: hostfolder-volume
              mountPath: /hostfolder
---
kind: Service
apiVersion: v1
metadata:
  name: greetings
  labels:
    app: greetings
spec:
  selector:
    app: greetings
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5001
    nodePort: 55555
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: greetings-config
  labels:
    app: greetings
data:
  filenames.txt: |
    application.py
    Dockerfile
    build.sh
    requirements.txt
    greetings.yaml
    README.txt
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: greetings
  namespace: default
  labels:
    app: greetings
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: greetings-reader-role
  namespace: default
  labels:
    app: greetings
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps", "serviceaccounts"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: greetings-reader-rolebinding
  namespace: default
  labels:
    app: greetings
subjects:
  - kind: ServiceAccount
    name: greetings
    namespace: default
roleRef:
  kind: Role
  name: greetings-reader-role
  apiGroup: rbac.authorization.k8s.io
